### ISSUE TITLE
V3 with dep

### ISSUE THREAD

**Issue by montanaflynn** [ulule/limiter#57] opened 2019-04-16 08:41 UTC
How can I use this package if I'm using dep rather than modules?

When I run `dep ensure` I get these errors:

```
Solving failure: No versions of github.com/ulule/limiter met constraints:
	v3.1.0: Could not introduce github.com/ulule/limiter@v3.1.0, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v3.0.0: Could not introduce github.com/ulule/limiter@v3.0.0, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2.2.2: Could not introduce github.com/ulule/limiter@v2.2.2, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2.2.1: Could not introduce github.com/ulule/limiter@v2.2.1, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2.2.0: Could not introduce github.com/ulule/limiter@v2.2.0, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2.1.0: Could not introduce github.com/ulule/limiter@v2.1.0, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2.0.0: Could not introduce github.com/ulule/limiter@v2.0.0, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v1.0.0: Could not introduce github.com/ulule/limiter@v1.0.0 due to multiple problematic subpackages:
	Subpackage github.com/ulule/limiter/drivers/middleware/stdlib is missing. (Package is required by (root).)	Subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	master: Could not introduce github.com/ulule/limiter@master, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	dev: Could not introduce github.com/ulule/limiter@dev, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v1: Could not introduce github.com/ulule/limiter@v1 due to multiple problematic subpackages:
	Subpackage github.com/ulule/limiter/drivers/middleware/stdlib is missing. (Package is required by (root).)	Subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
	v2: Could not introduce github.com/ulule/limiter@v2, as its subpackage github.com/ulule/limiter/v3/drivers/store/redis is missing. (Package is required by (root).)
```

**Comment by novln** [comment] 2019-04-16 10:11
Hello,

I'm not familiar with the cohabitation of dep and go modules...
Could you try to import `github.com/ulule/limiter/v3` with dep?

If that doesn't solve the problems, can you tell me? 
I'll have to create another branch to remove the versioning in the import path.

Thank you.

**Comment by montanaflynn** [comment] 2019-04-16 11:46
I could not use v3 with dep:

```
dep ensure -add github.com/ulule/limiter/v3
Fetching sources...

Solving failure: No versions of github.com/ulule/limiter met constraints:
	v3.1.0: Could not introduce github.com/ulule/limiter@v3.1.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v3.0.0: Could not introduce github.com/ulule/limiter@v3.0.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2.2.2: Could not introduce github.com/ulule/limiter@v2.2.2, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2.2.1: Could not introduce github.com/ulule/limiter@v2.2.1, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2.2.0: Could not introduce github.com/ulule/limiter@v2.2.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2.1.0: Could not introduce github.com/ulule/limiter@v2.1.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2.0.0: Could not introduce github.com/ulule/limiter@v2.0.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v1.0.0: Could not introduce github.com/ulule/limiter@v1.0.0, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	master: Could not introduce github.com/ulule/limiter@master, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	dev: Could not introduce github.com/ulule/limiter@dev, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v1: Could not introduce github.com/ulule/limiter@v1, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
	v2: Could not introduce github.com/ulule/limiter@v2, as its subpackage github.com/ulule/limiter/v3 is missing. (Package is required by (root).)
```

**Comment by novln** [comment] 2019-04-16 11:48
Creating a new branch it is...
Thanks for the report.

**Comment by novln** [comment] 2019-04-17 20:14
@montanaflynn Could you try the `v3-dep` branch?

**Comment by novln** [comment] 2019-04-30 11:26
@montanaflynn If it fixes this issue, could you close it?
Thank you.

**Comment by moizjv** [comment] 2019-05-01 20:04
Still not importing drivers subfolder.
Following dep config works with a workaround

```
[[constraint]]
  name = "github.com/ulule/limiter"
  branch = "v3-dep"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "github.com/ulule/limiter"
    unused-packages = false
```

**Comment by domgolonka** [comment] 2019-07-14 19:34
Im still getting the same error even after trying the v3-dep branch.

**Comment by novln** [comment] 2019-07-15 08:25
@domgolonka Have you tried moizjv workaround?

If it doesn't work, I'll gladly review any pull request that tries to fix this incompatibility between dep and go modules. Unfortunately, I don't have much time to take a deeper look at this issue.

**Comment by novln** [comment] 2019-07-18 15:16
Sorry I'm unable to reproduce this error using an up-to-date version of `dep`

```bash
➤ dep version
dep:
 version     : v0.5.4
 build date  : 2019-06-14
```

Please make sure that you are using the branch `v3-dep`

This is the project I used as reference: https://github.com/novln/limiter-dep-demo

**Comment by thoas** [comment] 2019-08-06 06:41
closing the issue, it's time to migrate to `go mod`

**Closed by thoas** 2019-08-06 06:41 UTC
